version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - "./jenkins-data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    platform: linux/x86_64
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - jenkins
    environment:
      POSTGRES_USER: marcelinne
      POSTGRES_PASSWORD: 1206copo
      POSTGRES_DB: debate

    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
  
     

networks:
  jenkins:

